apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Test-k8sCluster
  region: us-east-1


vpc:
  id: "vpc-XXXXXXXXXXXX"
  cidr: "10.10.0.0/16"
  subnets:
    private:
      us-east-1a:
          id: "subnet-XXXXXXXXXXXXXXXX"
      us-east-1b:
          id: "subnet-XXXXXXXXXXXXXXXX"
    public:
      us-east-1a:
          id: "subnet-XXXXXXXXXXXXXXXX"
      us-east-1b:
          id: "subnet-XXXXXXXXXXXXXXXX"

nodeGroups:
  - name: Test-k8sCluster-node-group-1
    instanceType: c6g.large
    desiredCapacity: 2
    maxSize: 6
    #availabilityZones: ["us-east-1a","us-east-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true  #enabling the autoscaling
    labels:
      application-type: nlp-services    #nodegroup-type: stateful-east1c
      instance-type: onDemand            
    ssh: # use existing EC2 key
      #allow:  true
      publicKeyName:  eks-raj
    privateNetworking: true
    subnets:
      - us-east-1a
      - us-east-1b


